### PR TITLE
apt-file like new 'search-file' command

### PR DESCRIPTION
**Pull request by chybz**
Hi iMil,

while working on some project, I needed an `apt-file search foo.h` feature but to the best of my knowledge, it is not available for non-installed packages. So I decided to create one for pkgin.

Please note that it needs some support from `pkg_info`. I added a new `-Y` option to it that outputs what is needed for the `search-file` command. The modified pkg_info is available here:

https://github.com/yrmt/pkgsrc/commit/eed914709e8e9e691c03ca78bbe15af0b56038c9

What do you think about it ?

### CODE REVIEW

**Comment by yrmt** [comment]
I am currently updating this patchset for current pkgin (using existing libarchive code) but I don't have access to your changes on pkg_install @chybz, could I have them?

**Comment by chybz** [comment]
> On 11 Feb 2016, at 22:17, Youri Mouton <notifications@github.com> wrote:
> 
> I am currently updating this patchset for current pkgin (using existing libarchive code) but I don't have access to your changes on pkg_install @chybz, could I have them?

Hey there,

please forget this patch: it needs pkg_info modifications and I received strong opposition on this subject (please see pkg/49117 on gnats). The main idea was to support “apt-file” like functionality with only basic pkgsrc tools and a remote binary repository.

I’ve relied on other available information (but that requires a full pkgsrc tree) for my needs.

Given the less than overwhelming response I had for just a few lines patch for pkg_info, I’m not that inclined to proceed any further.

I you’re still eager to proceed, I’ll dig my “dev” folder for you and extract all code I possibly kept on this subject.

Once again, thanks for your great work and commitment.

Sincerely,

-- 
    Rémy

**Comment by yrmt** [comment]
I am indeed still eager to work on this, even if I realise agc or joerg will probably deny this patch :(

**Comment by chybz** [comment]
> On 11 Feb 2016, at 23:00, Youri Mouton <notifications@github.com> wrote:
> 
> I am indeed still eager to work on this, even if I realise agc or joerg will probably deny this patch :(

Being the stubborn person and asshole I am, all source code has disappeared from my machine.

I thing you’ll find the relevant bits here:

http://gnats.netbsd.org/cgi-bin/query-pr-single.pl?number=49117

though you might have to reconstruct a proper patch.

I’m sorry for any supplementary work your side.

Best wishes,

-- 
    Rémy

**Comment by yrmt** [comment]
Hey @chybz, I've restored your diff from gnats on my local pkgsrc fork https://github.com/yrmt/pkgsrc/commit/3402ad28561cb245fab970fac904c9a5ce524c2d. I'm currently working on the pkgin diff which I'll post here as well.

**Comment by nbyouri** [comment]
After some thinking, it seems like this change isn't possible without being very intrusive, @chybz could you close it?

**Comment by chybz** [comment]
Sure ! Thanks for your help

**Pull request closed without merging**
